// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainleftDriveLead;
    public static CANTalon driveTrainrightDriveLead;
    public static RobotDrive driveTraindriveTrain;
    public static DoubleSolenoid driveTrainshifter;
    public static CANTalon collectorcollectorMotor;
    public static DigitalInput collectorboulderSensor;
    public static CANTalon shooterleftShooter;
    public static CANTalon shooterrightShooter;
    public static CANTalon armarmMotor;
    public static CANTalon climberclimberMotor;
    public static Relay towerCameratowerRelay;
    public static Compressor compressorcompressor;
    public static AnalogInput compressorpressureSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleftDriveLead = new CANTalon(0);
        LiveWindow.addActuator("driveTrain", "leftDriveLead", driveTrainleftDriveLead);
        
        driveTrainrightDriveLead = new CANTalon(2);
        LiveWindow.addActuator("driveTrain", "rightDriveLead", driveTrainrightDriveLead);
        
        driveTraindriveTrain = new RobotDrive(driveTrainleftDriveLead, driveTrainrightDriveLead);
        
        driveTraindriveTrain.setSafetyEnabled(true);
        driveTraindriveTrain.setExpiration(0.1);
        driveTraindriveTrain.setSensitivity(0.5);
        driveTraindriveTrain.setMaxOutput(1.0);

        driveTrainshifter = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("driveTrain", "shifter", driveTrainshifter);
        
        collectorcollectorMotor = new CANTalon(6);
        LiveWindow.addActuator("collector", "collectorMotor", collectorcollectorMotor);
        
        collectorboulderSensor = new DigitalInput(0);
        LiveWindow.addSensor("collector", "boulderSensor", collectorboulderSensor);
        
        shooterleftShooter = new CANTalon(4);
        LiveWindow.addActuator("shooter", "leftShooter", shooterleftShooter);
        
        shooterrightShooter = new CANTalon(5);
        LiveWindow.addActuator("shooter", "rightShooter", shooterrightShooter);
        
        armarmMotor = new CANTalon(7);
        LiveWindow.addActuator("arm", "armMotor", armarmMotor);
        
        climberclimberMotor = new CANTalon(8);
        LiveWindow.addActuator("climber", "climberMotor", climberclimberMotor);
        
        towerCameratowerRelay = new Relay(0);
        LiveWindow.addActuator("towerCamera", "towerRelay", towerCameratowerRelay);
        
        compressorcompressor = new Compressor(0);
        
        
        compressorpressureSensor = new AnalogInput(0);
        LiveWindow.addSensor("compressor", "pressureSensor", compressorpressureSensor);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
